# --- Базовые правила Kotlin ---
-keep class kotlin.Metadata { *; }
-keepclassmembers class ** {
    @org.koin.core.annotation.** *;
}

# --- Koin (Dependency Injection) ---
-keep class org.koin.** { *; }
-keep interface org.koin.** { *; }

# --- Voyager (Navigation) ---
-keep class cafe.adriel.voyager.** { *; }
-keep interface cafe.adriel.voyager.** { *; }

# --- SQLDelight ---
-keep class com.squareup.sqldelight.** { *; }

# --- Firebase ---
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.internal.** { *; }

# --- Compose Multiplatform ---
-keep class androidx.compose.** { *; }
-keep class org.jetbrains.compose.** { *; }

# --- Ktor & Serialization ---
-keep class kotlinx.serialization.json.** { *; }
-keepclassmembernames class kotlinx.serialization.json.** { *; }
-keepattributes Signature, Annotation, EnclosingMethod, InnerClasses

# --- Napier (Логгер) ---
-keep class io.github.aakira.napier.** { *; }

# --- Suppress Warnings (Generated by R8) ---
-dontwarn com.google.firebase.ktx.Firebase
-dontwarn com.google.firebase.ktx.FirebaseKt
-dontwarn org.koin.compose.stable.StableHoldersKt
-dontwarn org.koin.compose.stable.StableParametersDefinition

# --- Сохраняем UI-стейты и модели ---
-keep class com.ykis.ykismobkmp.ui.** { *; }
-keep class com.ykis.ykismobkmp.domain.models.** { *; }
