# --- Базовые правила Kotlin ---
-keepattributes Signature, Annotation, EnclosingMethod, InnerClasses
-keep class kotlin.Metadata { *; }

# --- Koin (Dependency Injection) ---
# Koin предоставляет свои правила, оставляем только поддержку аннотаций если они используются
-keepclassmembers class ** {
    @org.koin.core.annotation.** *;
}

# --- kotlinx.serialization ---
# Сохраняем классы помеченные @Serializable и их сериализаторы
-keepattributes *Annotation*, Signature
-keep @kotlinx.serialization.Serializable class * { *; }
-keepclassmembers class * {
    @kotlinx.serialization.SerialName <fields>;
}
-keepclassmembers class **$serializer {
    public static INSTANCE;
}

# --- Сохраняем UI-стейты и доменные сущности (важно для десериализации) ---
-keep class com.ykis.ykismobkmp.ui.BaseUIState { *; }
-keep class com.ykis.ykismobkmp.domain.entity.** { *; }

# --- Suppress Warnings (Generated by R8) ---
-dontwarn com.google.firebase.ktx.Firebase
-dontwarn com.google.firebase.ktx.FirebaseKt
-dontwarn org.koin.compose.stable.StableHoldersKt
-dontwarn org.koin.compose.stable.StableParametersDefinition
